name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:
    env:
      PYTHONIOENCODING: utf-8
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Package application (MacOS)
        if: runner.os == 'macOS'
        run: |
          virtualenv venv
          source venv/bin/activate
          maturin develop --release
          pyinstaller -F -n ignis -i ignis.ico ignis/ui/main.py
          rm -rf dist/ignis.app
          cp ignis.ico dist/ignis.ico
          cp -R Data dist/Data
          cp -R LICENSE.txt dist/LICENSE.txt

      - name: Package application (Windows)
        if: runner.os == 'Windows'
        run: |
          virtualenv venv
          .\venv\Scripts\activate.bat
          maturin develop --release
          pyinstaller -F -n ignis -i ignis.ico ignis\ui\main.py
          copy ignis.ico dist
          copy LICENSE.txt dist
          xcopy Data dist\Data\ /s /e /y

      - uses: actions/upload-artifact@v2
        with:
          name: ignis-${{ runner.os }}
          path: dist
